-- Inserts de las Comunidades Autónomas, ignora si se produce un error en la insercción
INSERT IGNORE INTO regions (id, code, name) VALUES
(1, '01', 'ANDALUCÍA'),
(2, '02', 'ARAGÓN'),
(3, '03', 'ASTURIAS'),
(4, '04', 'BALEARES'),
(5, '05', 'CANARIAS'),
(6, '06', 'CANTABRIA'),
(7, '07', 'CASTILLA Y LEÓN'),
(8, '08', 'CASTILLA-LA MANCHA'),
(9, '09', 'CATALUÑA'),
(10, '10', 'COMUNIDAD VALENCIANA'),
(11, '11', 'EXTREMADURA'),
(12, '12', 'GALICIA'),
(13, '13', 'MADRID'),
(14, '14', 'MURCIA'),
(15, '15', 'NAVARRA'),
(16, '16', 'PAÍS VASCO'),
(17, '17', 'LA RIOJA'),
(18, '18', 'CEUTA Y MELILLA');

-- Inserciones de provincias (una por cada región)
INSERT IGNORE INTO provinces (id, code, name) VALUES
(1, 'AL', 'SEVILLA'),
(2, 'AR', 'ZARAGOZA'),
(3, 'AS', 'OVIEDO'),
(4, 'IB', 'PALMA DE MALLORCA'),
(5, 'CN', 'LAS PALMAS'),
(6, 'CB', 'SANTANDER'),
(7, 'CL', 'VALLADOLID'),
(8, 'CM', 'TOLEDO'),
(9, 'CT', 'BARCELONA'),
(10, 'CV', 'VALENCIA'),
(11, 'EX', 'CÁCERES'),
(12, 'GA', 'A CORUÑA'),
(13, 'MD', 'MADRID'),
(14, 'MU', 'MURCIA'),
(15, 'NA', 'PAMPLONA'),
(16, 'PV', 'BILBAO'),
(17, 'LR', 'LOGROÑO'),
(18, 'CM', 'CEUTA');